package com.example.guess_the_number

data class City(
    val name: String,
    val country: String,
    val timezone: String,
    val population: Int
)

val cities = listOf(
    City("Dietikon / Oberdorf", "Switzerland", "Europe/Zurich", 4147),
    City("Muehlehalde", "Switzerland", "Europe/Zurich", 1220),
    City("Opfikon", "Switzerland", "Europe/Zurich", 1277),
    City("Kloten", "Switzerland", "Europe/Zurich", 16289),
    City("Hombrechtikon", "Switzerland", "Europe/Zurich", 9212),
    City("Glattfelden", "Switzerland", "Europe/Zurich", 2578),
    City("Dielsdorf", "Switzerland", "Europe/Zurich", 4671),
    City("Dachsen", "Switzerland", "Europe/Zurich", 1470),
    City("Kloten / Geissberg", "Switzerland", "Europe/Zurich", 1941),
    City("Richterswil / Richterswil (Dorfkern)", "Switzerland", "Europe/Zurich", 3292),
    City("Volketswil / Volketswil (Dorf)", "Switzerland", "Europe/Zurich", 2723),
    City("Au / Unter-Dorf", "Switzerland", "Europe/Zurich", 1249),
    City("Zuerich (Kreis 11) / Affoltern", "Switzerland", "Europe/Zurich", 17241),
    City("Zuerich (Kreis 2) / Enge", "Switzerland", "Europe/Zurich", 8253),
    City("Zuerich (Kreis 4) / Werd", "Switzerland", "Europe/Zurich", 3911),
    City("Steinmaur", "Switzerland", "Europe/Zurich", 1438),
    City("Gockhausen", "Switzerland", "Europe/Zurich", 1411),
    City("Aeugst am Albis", "Switzerland", "Europe/Zurich", 0),
    City("Zurich", "Switzerland", "Europe/Zurich", 341730),
    City("Veltheim", "Switzerland", "Europe/Zurich", 8901),
    City("Kloten / Spitz", "Switzerland", "Europe/Zurich", 1153),
    City("Urdorf / Bodenfeld", "Switzerland", "Europe/Zurich", 1840),
    City("Bubikon", "Switzerland", "Europe/Zurich", 2052),
    City("Mettmenstetten", "Switzerland", "Europe/Zurich", 2798),
    City("Neftenbach / Dorf Neftenbach", "Switzerland", "Europe/Zurich", 3171),
    City("Oetwil am See", "Switzerland", "Europe/Zurich", 4925),
    City("Rafz", "Switzerland", "Europe/Zurich", 3233),
    City("Zumikon", "Switzerland", "Europe/Zurich", 4424),
    City("Zuerich (Kreis 3) / Sihlfeld", "Switzerland", "Europe/Zurich", 20977),
    City("Oberwinterthur (Kreis 2) / Guggenbuehl", "Switzerland", "Europe/Zurich", 5376),
    City("Bulach", "Switzerland", "Europe/Zurich", 13172),
    City("Duebendorf / Kunklerstrasse", "Switzerland", "Europe/Zurich", 1284),
    City("Horgen / Scheller-Stockerstrasse", "Switzerland", "Europe/Zurich", 2690),
    City("Rueti / Westlicher Dorfteil", "Switzerland", "Europe/Zurich", 3083),
    City("Ruemlang / Ruemlang (Dorfkern)", "Switzerland", "Europe/Zurich", 3528),
    City("Oberglatt / Bahnhofquartier", "Switzerland", "Europe/Zurich", 1333),
    City("Sellenbueren", "Switzerland", "Europe/Zurich", 1572),
    City("Au", "Switzerland", "Europe/Zurich", 4844),
    City("Zuerich (Kreis 7) / Hottingen", "Switzerland", "Europe/Zurich", 9934),
    City("Zuerich (Kreis 6) / Unterstrass", "Switzerland", "Europe/Zurich", 20045),
    City("Zuerich (Kreis 12) / Saatlen", "Switzerland", "Europe/Zurich", 5209),
    City("Duebendorf / Sonnenberg", "Switzerland", "Europe/Zurich", 1018),
    City("Oberwinterthur (Kreis 2) / Hegi", "Switzerland", "Europe/Zurich", 1539),
    City("Gossau", "Switzerland", "Europe/Zurich", 4287),
    City("Effretikon", "Switzerland", "Europe/Zurich", 10119),
    City("Wallisellen / Wallisellen-Ost", "Switzerland", "Europe/Zurich", 5031),
    City("Binzikon", "Switzerland", "Europe/Zurich", 1854),
    City("Thalwil / Berg", "Switzerland", "Europe/Zurich", 1568),
    City("Kuesnacht / Itschnach", "Switzerland", "Europe/Zurich", 2397),
    City("Seuzach Dorf / Breite-Weid", "Switzerland", "Europe/Zurich", 1016),
    City("Kollbrunn / Kollbrunn (Dorfkern)", "Switzerland", "Europe/Zurich", 1040),
    City("Wuelflingen (Kreis 6) / Haerti", "Switzerland", "Europe/Zurich", 2602),
    City("Zuerich (Kreis 2) / Mittel-Leimbach", "Switzerland", "Europe/Zurich", 1891),
    City("Zuerich (Kreis 7) / Fluntern", "Switzerland", "Europe/Zurich", 7009),
    City("Zuerich (Kreis 8) / Seefeld", "Switzerland", "Europe/Zurich", 4998),
    City("Zuerich (Kreis 12)", "Switzerland", "Europe/Zurich", 28189),
    City("Elsau-Raeterschen", "Switzerland", "Europe/Zurich", 1395),
    City("Oberwinterthur (Kreis 2)", "Switzerland", "Europe/Zurich", 16356),
    City("Kollbrunn", "Switzerland", "Europe/Zurich", 1848),
    City("Kuesnacht", "Switzerland", "Europe/Zurich", 11525),
    City("Pfaffikon", "Switzerland", "Europe/Zurich", 7994),
    City("Schlieren", "Switzerland", "Europe/Zurich", 12695),
    City("Stadt Winterthur (Kreis 1) / Lind", "Switzerland", "Europe/Zurich", 4617),
    City("Wangen", "Switzerland", "Europe/Zurich", 2015),
    City("Wettswil", "Switzerland", "Europe/Zurich", 0),
    City("Obermeilen", "Switzerland", "Europe/Zurich", 2871),
    City("Schwerzenbach", "Switzerland", "Europe/Zurich", 4180),
    City("Zuerich (Kreis 7) / Hirslanden", "Switzerland", "Europe/Zurich", 6769),
    City("Zuerich (Kreis 1) / Lindenhof", "Switzerland", "Europe/Zurich", 1298),
    City("Weisslingen", "Switzerland", "Europe/Zurich", 1975),
    City("Uster / Gschwader", "Switzerland", "Europe/Zurich", 1763),
    City("Richterswil / Dorfkern", "Switzerland", "Europe/Zurich", 1216),
    City("Horgen", "Switzerland", "Europe/Zurich", 15973),
    City("Maennedorf", "Switzerland", "Europe/Zurich", 7951),
    City("Tann", "Switzerland", "Europe/Zurich", 3034),
    City("Waedenswil / Hangenmoos", "Switzerland", "Europe/Zurich", 1407),
    City("Uetikon", "Switzerland", "Europe/Zurich", 3431),
    City("Birmensdorf", "Switzerland", "Europe/Zurich", 4772),
    City("Adliswil / Sood", "Switzerland", "Europe/Zurich", 1494),
    City("Baretswil", "Switzerland", "Europe/Zurich", 1313),
    City("Elsau-Raeterschen / Raeterschen", "Switzerland", "Europe/Zurich", 1071),
    City("Oberwinterthur (Kreis 2) / Talacker", "Switzerland", "Europe/Zurich", 5375),
    City("Gutenswil", "Switzerland", "Europe/Zurich", 1188),
    City("Thalwil / Nord", "Switzerland", "Europe/Zurich", 1751),
    City("Adliswil / Huendli-Zopf", "Switzerland", "Europe/Zurich", 1553),
    City("Brutten", "Switzerland", "Europe/Zurich", 1556),
    City("Herrliberg", "Switzerland", "Europe/Zurich", 5025),
    City("Hittnau / Hittnau (Dorf)", "Switzerland", "Europe/Zurich", 1502),
    City("Turbenthal", "Switzerland", "Europe/Zurich", 3109),
    City("Dietikon / Vorstadt", "Switzerland", "Europe/Zurich", 2619),
    City("Uster", "Switzerland", "Europe/Zurich", 23279),
    City("Waedenswil", "Switzerland", "Europe/Zurich", 13269),
    City("Weiningen", "Switzerland", "Europe/Zurich", 1753),
    City("Illnau / Unter-Illnau", "Switzerland", "Europe/Zurich", 2011),
    City("Zuerich (Kreis 11) / Seebach", "Switzerland", "Europe/Zurich", 17851),
    City("Russikon", "Switzerland", "Europe/Zurich", 2415),
    City("Zuerich (Kreis 7)", "Switzerland", "Europe/Zurich", 33820),
    City("Veltheim (Kreis 5) / Blumenau", "Switzerland", "Europe/Zurich", 4135),
    City("Dietikon / Guggenbuehl", "Switzerland", "Europe/Zurich", 1312),
    City("Schwerzenbach / Chimli", "Switzerland", "Europe/Zurich", 1020),
    City("Hausen am Albis / Hausen (Dorf)", "Switzerland", "Europe/Zurich", 3253),
    City("Wuelflingen (Kreis 6) / Oberfeld", "Switzerland", "Europe/Zurich", 4288),
    City("Dietikon / Schoenenwerd", "Switzerland", "Europe/Zurich", 1218),
    City("Schlieren / Zentrum", "Switzerland", "Europe/Zurich", 1207),
    City("Zuerich (Kreis 12) / Auzelg", "Switzerland", "Europe/Zurich", 1143),
    City("Zuerich (Kreis 4) / Langstrasse", "Switzerland", "Europe/Zurich", 10386),
    City("Toss", "Switzerland", "Europe/Zurich", 8672),
    City("Oberengstringen", "Switzerland", "Europe/Zurich", 5805),
    City("Wettswil / Wettswil (Dorf)", "Switzerland", "Europe/Zurich", 3605),
    City("Schlieren / Boden", "Switzerland", "Europe/Zurich", 1241),
    City("Erlenbach / rechts des Dorfbachs oberhalb Bahnlinie", "Switzerland", "Europe/Zurich", 1470),
    City("Maennedorf / Ausserfeld", "Switzerland", "Europe/Zurich", 1175),
    City("Mattenbach (Kreis 7)", "Switzerland", "Europe/Zurich", 11043),
    City("Zuerich (Kreis 1)", "Switzerland", "Europe/Zurich", 6185),
    City("Zuerich (Kreis 9) / Altstetten", "Switzerland", "Europe/Zurich", 28307),
    City("Zuerich (Kreis 3) / Friesenberg", "Switzerland", "Europe/Zurich", 9909),
    City("Zuerich (Kreis 12) / Hirzenbach", "Switzerland", "Europe/Zurich", 11335),
    City("Ebmatingen", "Switzerland", "Europe/Zurich", 2278),
    City("Seen (Kreis 3) / Waldegg", "Switzerland", "Europe/Zurich", 1184),
    City("Hinteregg", "Switzerland", "Europe/Zurich", 1107),
    City("Naenikon / Naenikon (Dorfkern)", "Switzerland", "Europe/Zurich", 1178),
    City("Hettlingen", "Switzerland", "Europe/Zurich", 2221),
    City("Henggart", "Switzerland", "Europe/Zurich", 1574),
    City("Neerach", "Switzerland", "Europe/Zurich", 1435),
    City("Oberglatt / Oberglatt (Dorfkern)", "Switzerland", "Europe/Zurich", 1406),
    City("Horgen / Horgen (Dorfkern)", "Switzerland", "Europe/Zurich", 6140),
    City("Erlenbach / links des Dorfbachs oberhalb Bahnlinie", "Switzerland", "Europe/Zurich", 1709),
    City("Duebendorf / Vogelquartier", "Switzerland", "Europe/Zurich", 1391),
    City("Zuerich (Kreis 12) / Schwamendingen-Mitte", "Switzerland", "Europe/Zurich", 10476),
    City("Uetikon / Grossdorf", "Switzerland", "Europe/Zurich", 1040),
    City("Daenikon", "Switzerland", "Europe/Zurich", 1682),
    City("Niederglatt", "Switzerland", "Europe/Zurich", 3632),
    City("Zuerich (Kreis 2)", "Switzerland", "Europe/Zurich", 29215),
    City("Hegnau", "Switzerland", "Europe/Zurich", 7961),
    City("Zuerich (Kreis 2) / Wollishofen", "Switzerland", "Europe/Zurich", 16073),
    City("Mattenbach (Kreis 7) / Gutschick", "Switzerland", "Europe/Zurich", 2923),
    City("Toess (Kreis 4) / Eichliacker", "Switzerland", "Europe/Zurich", 3626),
    City("Wetzikon / Ober-Wetzikon", "Switzerland", "Europe/Zurich", 3858),
    City("Zuerich (Kreis 5) / Gewerbeschule", "Switzerland", "Europe/Zurich", 9891),
    City("Mattenbach (Kreis 7) / Endliker", "Switzerland", "Europe/Zurich", 2169),
    City("Stadt Winterthur (Kreis 1) / Heiligberg", "Switzerland", "Europe/Zurich", 3034),
    City("Affoltern / Unterdorf", "Switzerland", "Europe/Zurich", 1989),
    City("Knonau", "Switzerland", "Europe/Zurich", 1077),
    City("Nurensdorf", "Switzerland", "Europe/Zurich", 2310),
    City("Rumlang", "Switzerland", "Europe/Zurich", 5144),
    City("Uhwiesen", "Switzerland", "Europe/Zurich", 1140),
    City("Richterswil", "Switzerland", "Europe/Zurich", 10189),
    City("Fallanden", "Switzerland", "Europe/Zurich", 2100),
    City("Bruttisellen", "Switzerland", "Europe/Zurich", 3697),
    City("Kloten / Kloten (Zentrum)", "Switzerland", "Europe/Zurich", 1681),
    City("Birchwil", "Switzerland", "Europe/Zurich", 1066),
    City("Niederglatt / Niederglatt (Dorfkern)", "Switzerland", "Europe/Zurich", 1147),
    City("Regensdorf / Hofacher-Geeren", "Switzerland", "Europe/Zurich", 1038),
    City("Regensdorf / Feldblumen-Riedthofstrasse", "Switzerland", "Europe/Zurich", 1122),
    City("Duebendorf / Wasserfurren", "Switzerland", "Europe/Zurich", 1060),
    City("Stadt Winterthur (Kreis 1) / Altstadt", "Switzerland", "Europe/Zurich", 1665),
    City("Seen (Kreis 3)", "Switzerland", "Europe/Zurich", 15434),
    City("Wuelflingen (Kreis 6)", "Switzerland", "Europe/Zurich", 12598),
    City("Zuerich (Kreis 8) / Weinegg", "Switzerland", "Europe/Zurich", 4951),
    City("Wald", "Switzerland", "Europe/Zurich", 3061),
    City("Dorf", "Switzerland", "Europe/Zurich", 1226),
    City("Kuesnacht / Dorf", "Switzerland", "Europe/Zurich", 1574),
    City("Waedenswil / Leihof-Muehlebach", "Switzerland", "Europe/Zurich", 1830),
    City("Adliswil / Sonnenberg", "Switzerland", "Europe/Zurich", 1283),
    City("Glattbrugg", "Switzerland", "Europe/Zurich", 2642),
    City("Meilen", "Switzerland", "Europe/Zurich", 4419),
    City("Wila", "Switzerland", "Europe/Zurich", 1387),
    City("Uerikon", "Switzerland", "Europe/Zurich", 1794),
    City("Aesch", "Switzerland", "Europe/Zurich", 1717),
    City("Langnau / Langnau (Dorf)", "Switzerland", "Europe/Zurich", 4745),
    City("Pfaeffikon / Irgenhausen", "Switzerland", "Europe/Zurich", 2032),
    City("Grossacker/Opfikon", "Switzerland", "Europe/Zurich", 1076),
    City("Horgen / Oberdorf", "Switzerland", "Europe/Zurich", 2524),
    City("Kilchberg / Baechler-Stocken", "Switzerland", "Europe/Zurich", 1147),
    City("Thalwil / Sued", "Switzerland", "Europe/Zurich", 1255),
    City("Mattenbach (Kreis 7) / Deutweg", "Switzerland", "Europe/Zurich", 5930),
    City("Esslingen", "Switzerland", "Europe/Zurich", 1203),
    City("Elgg / Staedtchen und Umgebung", "Switzerland", "Europe/Zurich", 2342),
    City("Schlieren / Kamp", "Switzerland", "Europe/Zurich", 1129),
    City("Daellikon / Daellikon (Dorf)", "Switzerland", "Europe/Zurich", 1583),
    City("Wuelflingen (Kreis 6) / Lindenplatz", "Switzerland", "Europe/Zurich", 2555),
    City("Toess (Kreis 4) / Schlosstal", "Switzerland", "Europe/Zurich", 2762),
    City("Schwerzenbach / Blatten", "Switzerland", "Europe/Zurich", 1078),
    City("Binz", "Switzerland", "Europe/Zurich", 1601),
    City("Pfaeffikon / Pfaeffikon (Dorfkern)", "Switzerland", "Europe/Zurich", 5595),
    City("Richterswil / Burghalde", "Switzerland", "Europe/Zurich", 1137),
    City("Kilchberg / Kilchberg (Dorfkern)", "Switzerland", "Europe/Zurich", 2244),
    City("Glattbrugg / Wydacker/Bettacker/Laettenwiesen", "Switzerland", "Europe/Zurich", 1551),
    City("Schlieren / Spital", "Switzerland", "Europe/Zurich", 2587),
    City("Buelach / Seematt", "Switzerland", "Europe/Zurich", 2171),
    City("Wettswil / Ausser-Dorf", "Switzerland", "Europe/Zurich", 1438),
    City("Obfelden / Toussen", "Switzerland", "Europe/Zurich", 1146),
    City("Obfelden / Oberlunnern", "Switzerland", "Europe/Zurich", 1103),
    City("Flurlingen", "Switzerland", "Europe/Zurich", 1221),
    City("Hinwil", "Switzerland", "Europe/Zurich", 5488),
    City("Zuerich (Kreis 6) / Oberstrass", "Switzerland", "Europe/Zurich", 9906),
    City("Oberengstringen / Zentrum", "Switzerland", "Europe/Zurich", 1271),
    City("Zuerich (Kreis 11)", "Switzerland", "Europe/Zurich", 54260),
    City("Thalwil / See", "Switzerland", "Europe/Zurich", 1893),
    City("Zuerich (Kreis 10)", "Switzerland", "Europe/Zurich", 36216),
    City("Stadt Winterthur (Kreis 1) / Bruehlberg", "Switzerland", "Europe/Zurich", 1476),
    City("Dietikon / Kreuzacker", "Switzerland", "Europe/Zurich", 1955),
    City("Urdorf / Moos", "Switzerland", "Europe/Zurich", 1266),
    City("Zuerich (Kreis 10) / Wipkingen", "Switzerland", "Europe/Zurich", 15718),
    City("Zuerich (Kreis 3)", "Switzerland", "Europe/Zurich", 46018),
    City("Geroldswil", "Switzerland", "Europe/Zurich", 3681),
    City("Wolfhausen", "Switzerland", "Europe/Zurich", 2402),
    City("Zuerich (Kreis 5)", "Switzerland", "Europe/Zurich", 11737),
    City("Stadt Winterthur (Kreis 1)", "Switzerland", "Europe/Zurich", 16182),
    City("Seen (Kreis 3) / Bueelwiesen", "Switzerland", "Europe/Zurich", 2632),
    City("Gattikon", "Switzerland", "Europe/Zurich", 2142),
    City("Wetzikon / Kempten", "Switzerland", "Europe/Zurich", 4377),
    City("Tann / Tann (Dorfkern)", "Switzerland", "Europe/Zurich", 2080),
    City("Sonnhalde", "Switzerland", "Europe/Zurich", 1984),
    City("Bonstetten", "Switzerland", "Europe/Zurich", 2260),
    City("Zuerich (Kreis 10) / Hoengg", "Switzerland", "Europe/Zurich", 17117),
    City("Effretikon / Watt", "Switzerland", "Europe/Zurich", 2632),
    City("Oberrieden / Mitte", "Switzerland", "Europe/Zurich", 1807),
    City("Horgen / Allmend", "Switzerland", "Europe/Zurich", 3809),
    City("Adliswil / Adliswil (Stadtkern)", "Switzerland", "Europe/Zurich", 2538),
    City("Oberengstringen / Rauchacher", "Switzerland", "Europe/Zurich", 1126),
    City("Dietikon / Hofacker", "Switzerland", "Europe/Zurich", 2826),
    City("Toess (Kreis 4) / Vorder-Daettnau", "Switzerland", "Europe/Zurich", 1476),
    City("Kuesnacht / Goldbach", "Switzerland", "Europe/Zurich", 2607),
    City("Thalwil / Dorfkern", "Switzerland", "Europe/Zurich", 6829),
    City("Rueti / Oberdorf", "Switzerland", "Europe/Zurich", 2875),
    City("Buelach / Soligaenter", "Switzerland", "Europe/Zurich", 1434),
    City("Erlenbach", "Switzerland", "Europe/Zurich", 4519),
    City("Nanikon", "Switzerland", "Europe/Zurich", 1560),
    City("Wallisellen", "Switzerland", "Europe/Zurich", 11705),
    City("Thalwil", "Switzerland", "Europe/Zurich", 13296),
    City("Schachen", "Switzerland", "Europe/Zurich", 1278),
    City("Hedingen", "Switzerland", "Europe/Zurich", 2835),
    City("Hofstetten", "Switzerland", "Europe/Zurich", 1115),
    City("Rueti / Dorfzentrum, Suedl. Teil", "Switzerland", "Europe/Zurich", 3618),
    City("Zuerich (Kreis 1) / Rathaus", "Switzerland", "Europe/Zurich", 3091),
    City("Zuerich (Kreis 5) / Escher-Wyss", "Switzerland", "Europe/Zurich", 1846),
    City("Oberwinterthur (Kreis 2) / Zinzikon", "Switzerland", "Europe/Zurich", 1842),
    City("Uster / Kirch-Uster", "Switzerland", "Europe/Zurich", 10428),
    City("Veltheim (Kreis 5) / Rosenberg", "Switzerland", "Europe/Zurich", 4765),
    City("Wuelflingen (Kreis 6) / Niederfeld", "Switzerland", "Europe/Zurich", 1227),
    City("Zuerich (Kreis 4) / Hard", "Switzerland", "Europe/Zurich", 12976),
    City("Zuerich (Kreis 9) / Albisrieden", "Switzerland", "Europe/Zurich", 16480),
    City("Zuerich (Kreis 1) / City", "Switzerland", "Europe/Zurich", 1089),
    City("Seen (Kreis 3) / Ganzenbuehl", "Switzerland", "Europe/Zurich", 2362),
    City("Seen (Kreis 3) / Waser", "Switzerland", "Europe/Zurich", 4088),
    City("Moenchaltorf / Dorf", "Switzerland", "Europe/Zurich", 1077),
    City("Embrach", "Switzerland", "Europe/Zurich", 7088),
    City("Waedenswil / Boller-Giessen", "Switzerland", "Europe/Zurich", 1538),
    City("Waedenswil / Eichweid", "Switzerland", "Europe/Zurich", 1252),
    City("Waedenswil / Bueelen", "Switzerland", "Europe/Zurich", 2710),
    City("Adliswil / Tal", "Switzerland", "Europe/Zurich", 1125),
    City("Adliswil / Oberleimbach", "Switzerland", "Europe/Zurich", 1411),
    City("Niederhasli", "Switzerland", "Europe/Zurich", 2848),
    City("Kloten / Hostrass", "Switzerland", "Europe/Zurich", 1012),
    City("Hegnau / Dammboden-Grindel", "Switzerland", "Europe/Zurich", 2817),
    City("Greifensee / Muellerwis / Seilerwis", "Switzerland", "Europe/Zurich", 1064),
    City("Effretikon / Rappenhalde-Bannhalde", "Switzerland", "Europe/Zurich", 1758),
    City("Langnau / Vitaquartier", "Switzerland", "Europe/Zurich", 1161),
    City("Oberengstringen / Sonnenberg", "Switzerland", "Europe/Zurich", 1477),
    City("Stadt Winterthur (Kreis 1) / Toessfeld", "Switzerland", "Europe/Zurich", 2207),
    City("Kloten / Balsberg", "Switzerland", "Europe/Zurich", 1389),
    City("Kloten / Horainli", "Switzerland", "Europe/Zurich", 1391),
    City("Embrach / Embrach (Dorfkern)", "Switzerland", "Europe/Zurich", 2960),
    City("Affoltern / Hasenbueel", "Switzerland", "Europe/Zurich", 1690),
    City("Elgg", "Switzerland", "Europe/Zurich", 3282),
    City("Marthalen", "Switzerland", "Europe/Zurich", 1567),
    City("Oberrieden", "Switzerland", "Europe/Zurich", 4413),
    City("Ober Urdorf", "Switzerland", "Europe/Zurich", 9205),
    City("Regensdorf", "Switzerland", "Europe/Zurich", 7531),
    City("Bassersdorf", "Switzerland", "Europe/Zurich", 7010),
    City("Bachenbulach", "Switzerland", "Europe/Zurich", 2985),
    City("Hochfelden", "Switzerland", "Europe/Zurich", 1442),
    City("Hoeri", "Switzerland", "Europe/Zurich", 1041),
    City("Buelach / Gstueckt", "Switzerland", "Europe/Zurich", 1863),
    City("Feldmeilen", "Switzerland", "Europe/Zurich", 3732),
    City("Uster / Ober-Uster", "Switzerland", "Europe/Zurich", 5100),
    City("Langnau am Albis", "Switzerland", "Europe/Zurich", 7000),
    City("Hadlikon", "Switzerland", "Europe/Zurich", 1321),
    City("Kuesnacht / Heslibach", "Switzerland", "Europe/Zurich", 3228),
    City("Hegnau / Sunnebueel-Eich", "Switzerland", "Europe/Zurich", 3250),
    City("Seen (Kreis 3) / Oberseen", "Switzerland", "Europe/Zurich", 2133),
    City("Dietikon / Almend", "Switzerland", "Europe/Zurich", 2118),
    City("Schlieren / Freiestrasse", "Switzerland", "Europe/Zurich", 1212),
    City("Zuerich (Kreis 6)", "Switzerland", "Europe/Zurich", 29951),
    City("Wetzikon / Unter-Wetzikon", "Switzerland", "Europe/Zurich", 2521),
    City("Greifensee", "Switzerland", "Europe/Zurich", 5032),
    City("Obfelden", "Switzerland", "Europe/Zurich", 4039),
    City("Durnten", "Switzerland", "Europe/Zurich", 1032),
    City("Kloten / Freienberg (Chanzler-Chlini Chaseren)", "Switzerland", "Europe/Zurich", 1588),
    City("Kuesnacht / Schiedhalden", "Switzerland", "Europe/Zurich", 1033),
    City("Tagelswangen", "Switzerland", "Europe/Zurich", 1606),
    City("Greifensee / Pfisterhoelzli", "Switzerland", "Europe/Zurich", 1135),
    City("Uster / Nieder-Uster", "Switzerland", "Europe/Zurich", 4128),
    City("Glattbrugg / Rohr/Platten-Balsberg", "Switzerland", "Europe/Zurich", 1780),
    City("Zuerich (Kreis 4) / Aussersihl", "Switzerland", "Europe/Zurich", 27273),
    City("Bauma", "Switzerland", "Europe/Zurich", 1029),
    City("Egg", "Switzerland", "Europe/Zurich", 4003),
    City("Effretikon / Rikon", "Switzerland", "Europe/Zurich", 1120),
    City("Zuerich (Kreis 3) / Alt-Wiedikon", "Switzerland", "Europe/Zurich", 14931),
    City("Wiesendangen / Wiesendangen (Dorf)", "Switzerland", "Europe/Zurich", 1649),
    City("Stafa", "Switzerland", "Europe/Zurich", 5737),
    City("Rorbas", "Switzerland", "Europe/Zurich", 1797),
    City("Fehraltorf", "Switzerland", "Europe/Zurich", 3767),
    City("Affoltern / Sonnenberg", "Switzerland", "Europe/Zurich", 1262),
    City("Dietlikon / Eichwiesen", "Switzerland", "Europe/Zurich", 1386),
    City("Wallisellen / Wallisellen-West", "Switzerland", "Europe/Zurich", 3511),
    City("Zuerich (Kreis 9)", "Switzerland", "Europe/Zurich", 44878),
    City("Zuerich (Kreis 8)", "Switzerland", "Europe/Zurich", 15519),
    City("Wetzikon", "Switzerland", "Europe/Zurich", 24764),
    City("Monchaltorf", "Switzerland", "Europe/Zurich", 2779),
    City("Kilchberg", "Switzerland", "Europe/Zurich", 6511),
    City("Feuerthalen", "Switzerland", "Europe/Zurich", 2165),
    City("Benglen", "Switzerland", "Europe/Zurich", 1937),
    City("Samstagern", "Switzerland", "Europe/Zurich", 3163),
    City("Winterthur", "Switzerland", "Europe/Zurich", 91908),
    City("Zuerich (Kreis 10) / Ruetihof", "Switzerland", "Europe/Zurich", 3326),
    City("Seuzach / Seuzach (Dorf)", "Switzerland", "Europe/Zurich", 1419),
    City("Zuerich (Kreis 7) / Witikon", "Switzerland", "Europe/Zurich", 9099),
    City("Urdorf / Oberurdorf", "Switzerland", "Europe/Zurich", 1008),
    City("Zuerich (Kreis 8) / Muehlebach", "Switzerland", "Europe/Zurich", 5570),
    City("Seglingen", "Switzerland", "Europe/Zurich", 1144),
    City("Seuzach Dorf", "Switzerland", "Europe/Zurich", 3969),
    City("Zuerich (Kreis 2) / Unter-Leimbach", "Switzerland", "Europe/Zurich", 2778),
    City("Uster / Nossikon", "Switzerland", "Europe/Zurich", 1433),
    City("Maennedorf / Dorfkern", "Switzerland", "Europe/Zurich", 4893),
    City("Pfungen", "Switzerland", "Europe/Zurich", 2369),
    City("Sulz", "Switzerland", "Europe/Zurich", 1244),
    City("Zuerich (Kreis 11) / Schwandenholz", "Switzerland", "Europe/Zurich", 1145),
    City("Waedenswil / Dorf (Waedenswil)", "Switzerland", "Europe/Zurich", 2556),
    City("Schlieren / Engstringerquartier", "Switzerland", "Europe/Zurich", 1877),
    City("Kindhausen / Kindhausen (Dorf)", "Switzerland", "Europe/Zurich", 1107),
    City("Au / Mittel-Dorf", "Switzerland", "Europe/Zurich", 2562),
    City("Embrach / Kellersacker", "Switzerland", "Europe/Zurich", 1467),
    City("Affoltern am Albis", "Switzerland", "Europe/Zurich", 8928),
    City("Dietikon", "Switzerland", "Europe/Zurich", 20893),
    City("Dietlikon / Dietlikon (Dorf)", "Switzerland", "Europe/Zurich", 6149),
    City("Dubendorf", "Switzerland", "Europe/Zurich", 19882),
    City("Ruschlikon", "Switzerland", "Europe/Zurich", 4653),
    City("Uitikon", "Switzerland", "Europe/Zurich", 3282),
    City("Zollikon", "Switzerland", "Europe/Zurich", 5812),
    City("Stadt Winterthur (Kreis 1) / Neuwiesen", "Switzerland", "Europe/Zurich", 3149),
    City("Zollikerberg", "Switzerland", "Europe/Zurich", 4187),
    City("Gruet", "Switzerland", "Europe/Zurich", 1565),
    City("Kloten / Ruetlen", "Switzerland", "Europe/Zurich", 2510),
    City("Zuerich (Kreis 11) / Oerlikon", "Switzerland", "Europe/Zurich", 17922),
    City("Illnau", "Switzerland", "Europe/Zurich", 2964),
    City("Unterengstringen", "Switzerland", "Europe/Zurich", 2675),
    City("Oberrieden / Berg", "Switzerland", "Europe/Zurich", 1961),
    City("Freienstein", "Switzerland", "Europe/Zurich", 1617),
    City("Kloten / Holberg", "Switzerland", "Europe/Zurich", 2239),
    City("Wallisellen / Rieden", "Switzerland", "Europe/Zurich", 2261),
    City("Rueti", "Switzerland", "Europe/Zurich", 9576),
    City("Pfaffhausen", "Switzerland", "Europe/Zurich", 1684),
    City("Otelfingen", "Switzerland", "Europe/Zurich", 1808),
    City("Oberglatt", "Switzerland", "Europe/Zurich", 3564),
    City("Regensdorf / Obstgarten", "Switzerland", "Europe/Zurich", 1090),
    City("Kleinandelfingen", "Switzerland", "Europe/Zurich", 1094),
    City("Affoltern / Oberdorf", "Switzerland", "Europe/Zurich", 1759),
    City("Ottenbach", "Switzerland", "Europe/Zurich", 2039),
    City("Adliswil", "Switzerland", "Europe/Zurich", 15230),
    City("Waedenswil / Untermosen-Fuhr", "Switzerland", "Europe/Zurich", 1976),
    City("Wetzikon / Robenhausen", "Switzerland", "Europe/Zurich", 2213),
    City("Andelfingen", "Switzerland", "Europe/Zurich", 1328),
    City("Baar", "Switzerland", "Europe/Zurich", 20546),
    City("Zug", "Switzerland", "Europe/Zurich", 23435),
    City("Hunenberg", "Switzerland", "Europe/Zurich", 9032),
    City("Steinhausen", "Switzerland", "Europe/Zurich", 8509),
    City("Rotkreuz", "Switzerland", "Europe/Zurich", 10439),
    City("Cham", "Switzerland", "Europe/Zurich", 16719),
    City("Walchwil", "Switzerland", "Europe/Zurich", 3268),
    City("Unterageri", "Switzerland", "Europe/Zurich", 7973),
    City("Menzingen", "Switzerland", "Europe/Zurich", 3878),
    City("Yona Village", "Guam", "Pacific/Guam", 6484),
    City("Yigo Village", "Guam", "Pacific/Guam", 20539),
    City("Ethete", "United States", "America/Denver", 1553),
    City("Thermopolis", "United States", "America/Denver", 2974),
    City("Pinedale", "United States", "America/Denver", 1923),
    City("Pine Bluffs", "United States", "America/Denver", 1146),
    City("Lander", "United States", "America/Denver", 7686),
    City("Fox Farm-College", "United States", "America/Denver", 3647),
    City("Basin", "United States", "America/Denver", 1305),
    City("Wilson", "United States", "America/Denver", 1482),
    City("Guernsey", "United States", "America/Denver", 1195),
    City("Mountain View", "United States", "America/Denver", 1294),
    City("Green River", "United States", "America/Denver", 12465),
    City("Wheatland", "United States", "America/Denver", 3659),
    City("Greybull", "United States", "America/Denver", 1879),
    City("Jackson", "United States", "America/Denver", 10523),
    City("Star Valley Ranch", "United States", "America/Denver", 1548),
    City("Moose Wilson Road", "United States", "America/Denver", 1821),
    City("Ranchettes", "United States", "America/Denver", 5798),
    City("Fort Washakie", "United States", "America/Denver", 1759),
    City("South Park", "United States", "America/Denver", 1731),
    City("Cody", "United States", "America/Denver", 9792),
    City("Lusk", "United States", "America/Denver", 1628),
    City("Moorcroft", "United States", "America/Denver", 1062),
    City("Wright", "United States", "America/Denver", 1862),
    City("Worland", "United States", "America/Denver", 5372),
    City("Arapahoe", "United States", "America/Denver", 1656),
    City("Newcastle", "United States", "America/Denver", 3534),
    City("Evanston", "United States", "America/Denver", 12133),
    City("Lyman", "United States", "America/Denver", 2074),
    City("Rawlins", "United States", "America/Denver", 9040),
    City("Kemmerer", "United States", "America/Denver", 2739),
    City("North Rock Springs", "United States", "America/Denver", 2207),
    City("Torrington", "United States", "America/Denver", 6669),
    City("Gillette", "United States", "America/Denver", 32649),
    City("Marbleton", "United States", "America/Denver", 1090),
    City("Rafter J Ranch", "United States", "America/Denver", 1075),
    City("Saratoga", "United States", "America/Denver", 1677),
    City("Antelope Valley-Crestview", "United States", "America/Denver", 1658),
    City("Lovell", "United States", "America/Denver", 2422),
    City("Cheyenne", "United States", "America/Denver", 63335),
    City("Rock Springs", "United States", "America/Denver", 23962),
    City("Sheridan", "United States", "America/Denver", 17873),
    City("Hoback", "United States", "America/Denver", 1176),
    City("Sleepy Hollow", "United States", "America/Denver", 1308),
    City("South Greeley", "United States", "America/Denver", 4217),
    City("Evansville", "United States", "America/Denver", 2931),
    City("Sundance", "United States", "America/Denver", 1272),
    City("Mills", "United States", "America/Denver", 3785),
    City("Bar Nunn", "United States", "America/Denver", 2820),
    City("Laramie", "United States", "America/Denver", 32158),
    City("Douglas", "United States", "America/Denver", 6531),
    City("Upton", "United States", "America/Denver", 1109),
    City("Buffalo", "United States", "America/Denver", 4632),
    City("Powell", "United States", "America/Denver", 6462),
    City("Riverton", "United States", "America/Denver", 10873),
    City("Glenrock", "United States", "America/Denver", 2598),
    City("Casper", "United States", "America/Denver", 60285),
    City("Afton", "United States", "America/Denver", 1972),
    City("Spencer", "United States", "America/New_York", 2195),
    City("Philippi", "United States", "America/New_York", 3256),
    City("Huntington", "United States", "America/New_York", 48638),
    City("Bethlehem", "United States", "America/New_York", 2588),
    City("Lewisburg", "United States", "America/New_York", 3949),
    City("Oak Hill", "United States", "America/New_York", 8140),
    City("White Sulphur Springs", "United States", "America/New_York", 2438),
    City("Shady Spring", "United States", "America/New_York", 2998),
    City("Ronceverte", "United States", "America/New_York", 1752),
    City("Shinnston", "United States", "America/New_York", 2171),
    City("Mount Gay-Shamrock", "United States", "America/New_York", 1779),
    City("Prosperity", "United States", "America/New_York", 1498),
    City("Star City", "United States", "America/New_York", 2014),
    City("Belington", "United States", "America/New_York", 1933),
    City("Weirton", "United States", "America/New_York", 19175),
    City("MacArthur", "United States", "America/New_York", 1500),
    City("Buckhannon", "United States", "America/New_York", 5657),
    City("Sistersville", "United States", "America/New_York", 1366),
    City("Mullens", "United States", "America/New_York", 1464),
    City("Mabscott", "United States", "America/New_York", 1372),
    City("Lavalette", "United States", "America/New_York", 1073),
    City("Beckley", "United States", "America/New_York", 17056),
    City("Lubeck", "United States", "America/New_York", 1311),
    City("Pinch", "United States", "America/New_York", 3262),
    City("New Martinsville", "United States", "America/New_York", 5218),
    City("Madison", "United States", "America/New_York", 2929),
    City("Fayetteville", "United States", "America/New_York", 2892),
    City("Bridgeport", "United States", "America/New_York", 8359),
    City("Blennerhassett", "United States", "America/New_York", 3089),
    City("Dunbar", "United States", "America/New_York", 7659),
    City("Cross Lanes", "United States", "America/New_York", 9995),
    City("Augusta", "United States", "America/New_York", 5734),
    City("Charleston", "United States", "America/New_York", 49736),
    City("Eleanor", "United States", "America/New_York", 1586),
    City("Clay", "United States", "America/New_York", 467),
    City("Kingwood", "United States", "America/New_York", 2959),
    City("West Liberty", "United States", "America/New_York", 1590),
    City("Chesapeake", "United States", "America/New_York", 1502),
    City("Berkeley Springs", "United States", "America/New_York", 766),
    City("Wheeling", "United States", "America/New_York", 27648),
    City("Barrackville", "United States", "America/New_York", 1321),
    City("Martinsburg", "United States", "America/New_York", 17700),
    City("Coal City", "United States", "America/New_York", 1815),
    City("Elizabeth", "United States", "America/New_York", 839),
    City("Franklin", "United States", "America/New_York", 677),
    City("Daniels", "United States", "America/New_York", 1881),
    City("Fort Ashby", "United States", "America/New_York", 1380),
    City("South Charleston", "United States", "America/New_York", 13045),
    City("Chester", "United States", "America/New_York", 2498),
    City("Bethany", "United States", "America/New_York", 1029),
    City("West Union", "United States", "America/New_York", 831),
    City("Follansbee", "United States", "America/New_York", 2887),
    City("Boaz", "United States", "America/New_York", 1297),
    City("Nitro", "United States", "America/New_York", 6763),
    City("Fairlea", "United States", "America/New_York", 1747),
    City("Petersburg", "United States", "America/New_York", 2520),
    City("Terra Alta", "United States", "America/New_York", 1493),
    City("Benwood", "United States", "America/New_York", 1361),
    City("Bethlehem", "United States", "America/New_York", 2425),
    City("Alderson", "United States", "America/New_York", 1182),
    City("Clarksburg", "United States", "America/New_York", 16152),
    City("Coal Fork", "United States", "America/New_York", 1233),
    City("Lesage", "United States", "America/New_York", 1358),
    City("Teays Valley", "United States", "America/New_York", 13175),
    City("Belle", "United States", "America/New_York", 1211),
    City("Princeton", "United States", "America/New_York", 6035),
    City("New Cumberland", "United States", "America/New_York", 1063),
    City("Weirton Heights", "United States", "America/New_York", 19450),
    City("Fairmont", "United States", "America/New_York", 18733),
    City("Hurricane", "United States", "America/New_York", 6493),
    City("Mannington", "United States", "America/New_York", 2077),
    City("Saint Marys", "United States", "America/New_York", 1860),
    City("New Haven", "United States", "America/New_York", 1532),
    City("Ripley", "United States", "America/New_York", 3255),
    City("Tornado", "United States", "America/New_York", 1081),
    City("Salem", "United States", "America/New_York", 1551),
    City("Ranson", "United States", "America/New_York", 4941),
    City("Beaver", "United States", "America/New_York", 1308),
    City("Wiley Ford", "United States", "America/New_York", 1026),
    City("Moundsville", "United States", "America/New_York", 8710),
    City("Milton", "United States", "America/New_York", 2637),
    City("Ceredo", "United States", "America/New_York", 1388),
    City("Bradley", "United States", "America/New_York", 2040),
    City("Ansted", "United States", "America/New_York", 1397),
    City("Westover", "United States", "America/New_York", 4223),
    City("Summersville", "United States", "America/New_York", 3478),
    City("Wellsburg", "United States", "America/New_York", 2704),
    City("Oceana", "United States", "America/New_York", 1302),
    City("Brush Fork", "United States", "America/New_York", 1197),
    City("Vienna", "United States", "America/New_York", 10573),
    City("Saint Albans", "United States", "America/New_York", 11044),
    City("Craigsville", "United States", "America/New_York", 2213),
    City("Clendenin", "United States", "America/New_York", 1187),
    City("Culloden", "United States", "America/New_York", 3061),
    City("Wayne", "United States", "America/New_York", 1382),
    City("Bluewell", "United States", "America/New_York", 2184),
    City("Glendale", "United States", "America/New_York", 1526),
    City("Washington", "United States", "America/New_York", 1175),
    City("Stonewood", "United States", "America/New_York", 1766),
    City("Shannondale", "United States", "America/New_York", 3358),
    City("Romney", "United States", "America/New_York", 1773),
    City("Gilbert Creek", "United States", "America/New_York", 1090),
    City("Pineville", "United States", "America/New_York", 628),
    City("Weston", "United States", "America/New_York", 4082),
    City("Marlinton", "United States", "America/New_York", 1029),
    City("Inwood", "United States", "America/New_York", 2954),
    City("McMechen", "United States", "America/New_York", 1842),
    City("Montgomery", "United States", "America/New_York", 1596),
    City("Nutter Fort", "United States", "America/New_York", 1575),
    City("Parkersburg", "United States", "America/New_York", 30991),
    City("Sissonville", "United States", "America/New_York", 4028),
    City("Despard", "United States", "America/New_York", 1004),
    City("Middlebourne", "United States", "America/New_York", 790),
    City("Welch", "United States", "America/New_York", 1973),
    City("Stanaford", "United States", "America/New_York", 1350),
    City("Williamson", "United States", "America/New_York", 3003),
    City("Ravenswood", "United States", "America/New_York", 3843),
    City("Mount Hope", "United States", "America/New_York", 1377),
    City("Keyser", "United States", "America/New_York", 5248),
    City("Hinton", "United States", "America/New_York", 2528),
    City("Crab Orchard", "United States", "America/New_York", 2678),
    City("Cheat Lake", "United States", "America/New_York", 7988),
    City("Charles Town", "United States", "America/New_York", 5899),
    City("Buffalo", "United States", "America/New_York", 1253),
    City("Richwood", "United States", "America/New_York", 1980),
    City("Rainelle", "United States", "America/New_York", 1481),
    City("Point Pleasant", "United States", "America/New_York", 4276),
    City("Kenova", "United States", "America/New_York", 3083),
    City("Sophia", "United States", "America/New_York", 1318),
    City("Pleasant Valley", "United States", "America/New_York", 3196),
    City("Pennsboro", "United States", "America/New_York", 1080),
    City("Morgantown", "United States", "America/New_York", 30708),
    City("Moorefield", "United States", "America/New_York", 2482),
    City("Mineral Wells", "United States", "America/New_York", 1950),
    City("Hamlin", "United States", "America/New_York", 1123),
    City("Sutton", "United States", "America/New_York", 984),
    City("Hooverson Heights", "United States", "America/New_York", 2590),
    City("Union", "United States", "America/New_York", 559),
    City("Rand", "United States", "America/New_York", 1631),
    City("Elkins", "United States", "America/New_York", 7226),
    City("Williamstown", "United States", "America/New_York", 2965),
    City("Logan", "United States", "America/New_York", 1649),
    City("Bolivar", "United States", "America/New_York", 1060),
    City("Marmet", "United States", "America/New_York", 1450),
    City("Pea Ridge", "United States", "America/New_York", 6650),
    City("Webster Springs", "United States", "America/New_York", 1009),
    City("Barboursville", "United States", "America/New_York", 4069),
    City("Alum Creek", "United States", "America/New_York", 1749),
    City("Bluefield", "United States", "America/New_York", 10323),
    City("Winfield", "United States", "America/New_York", 2354),
    City("Glenville", "United States", "America/New_York", 1543),
    City("Newell", "United States", "America/New_York", 1376),
    City("Elkview", "United States", "America/New_York", 1222),
    City("Granville", "United States", "America/New_York", 2554),
    City("Grafton", "United States", "America/New_York", 5148),
    City("Harrisville", "United States", "America/New_York", 1775),
    City("Brookhaven", "United States", "America/New_York", 5171),
    City("Chapmanville", "United States", "America/New_York", 1205),
    City("Grantsville", "United States", "America/New_York", 548),
    City("Mallory", "United States", "America/New_York", 1654),
    City("Monongah", "United States", "America/New_York", 1091),
    City("Paden City", "United States", "America/New_York", 2506),
    City("Shepherdstown", "United States", "America/New_York", 2079),
    City("Parsons", "United States", "America/New_York", 1431),
    City("Deganwy", "United Kingdom", "Europe/London", 9429),
    City("Freystrop", "United Kingdom", "Europe/London", 0),
    City("Denbigh", "United Kingdom", "Europe/London", 8514),
    City("Colwyn Bay", "United Kingdom", "Europe/London", 34284),
    City("Conwy", "United Kingdom", "Europe/London", 3873),
    City("Caerphilly", "United Kingdom", "Europe/London", 31060),
    City("Neath", "United Kingdom", "Europe/London", 46126),
    City("Crosskeys", "United Kingdom", "Europe/London", 0),
    City("Glyn-neath", "United Kingdom", "Europe/London", 5419),
    City("Aberaeron", "United Kingdom", "Europe/London", 1422),
    City("Gaerwen", "United Kingdom", "Europe/London", 1551),
    City("Marshfield", "United Kingdom", "Europe/London", 3054),
    City("Neyland", "United Kingdom", "Europe/London", 3708),
    City("Llangefni", "United Kingdom", "Europe/London", 4864),
    City("Crickhowell", "United Kingdom", "Europe/London", 2063),
    City("Hengoed", "United Kingdom", "Europe/London", 5044),
    City("Nash", "United Kingdom", "Europe/London", 0),
    City("Northop", "United Kingdom", "Europe/London", 1001),
    City("Saint Asaph", "United Kingdom", "Europe/London", 3355),
    City("Welshpool", "United Kingdom", "Europe/London", 5948),
    City("Halkyn", "United Kingdom", "Europe/London", 0),
    City("Porthcawl", "United Kingdom", "Europe/London", 15672),
    City("Llangwm", "United Kingdom", "Europe/London", 875),
    City("Pyle", "United Kingdom", "Europe/London", 13701),
    City("Trimsaran", "United Kingdom", "Europe/London", 1584),
    City("Penparcau", "United Kingdom", "Europe/London", 3088),
    City("Undy", "United Kingdom", "Europe/London", 5914),
    City("Goldcliff", "United Kingdom", "Europe/London", 0),
    City("Treherbert", "United Kingdom", "Europe/London", 0),
    City("Maesycwmmer", "United Kingdom", "Europe/London", 0),
    City("Whitland", "United Kingdom", "Europe/London", 1514),
    City("Tywyn", "United Kingdom", "Europe/London", 3097),
    City("Llanwinio", "United Kingdom", "Europe/London", 0),
    City("Llangybi", "United Kingdom", "Europe/London", 444),
    City("Llanwnda", "United Kingdom", "Europe/London", 0),
    City("Llangain", "United Kingdom", "Europe/London", 0),
    City("Benllech", "United Kingdom", "Europe/London", 2236),
    City("Caergwrle", "United Kingdom", "Europe/London", 4673),
    City("Risca", "United Kingdom", "Europe/London", 20443),
    City("Brymbo", "United Kingdom", "Europe/London", 18111),
    City("Dinas Powys", "United Kingdom", "Europe/London", 7738),
    City("Ffestiniog", "United Kingdom", "Europe/London", 0),
    City("Gresford", "United Kingdom", "Europe/London", 5010),
    City("Wick", "United Kingdom", "Europe/London", 698),
    City("Pentyrch", "United Kingdom", "Europe/London", 2287),
    City("Treuddyn", "United Kingdom", "Europe/London", 1360),
    City("Llandegla", "United Kingdom", "Europe/London", 0),
    City("Talysarn", "United Kingdom", "Europe/London", 1086),
    City("Hope", "United Kingdom", "Europe/London", 4706),
    City("Llanbadoc", "United Kingdom", "Europe/London", 0),
    City("Landore", "United Kingdom", "Europe/London", 0),
    City("Saint Davids", "United Kingdom", "Europe/London", 1800),
    City("Aberkenfig", "United Kingdom", "Europe/London", 10083),
    City("Bagillt", "United Kingdom", "Europe/London", 2749),
    City("Tal-y-bont", "United Kingdom", "Europe/London", 1540),
    City("Bishopston", "United Kingdom", "Europe/London", 3647),
    City("Caerwent", "United Kingdom", "Europe/London", 1201),
    City("Barry", "United Kingdom", "Europe/London", 54673),
    City("Burry Port", "United Kingdom", "Europe/London", 8310),
    City("Chirk", "United Kingdom", "Europe/London", 4007),
    City("Llanfaethlu", "United Kingdom", "Europe/London", 0),
    City("Bodelwyddan", "United Kingdom", "Europe/London", 1794),
    City("Bishton", "United Kingdom", "Europe/London", 0),
    City("Cray", "United Kingdom", "Europe/London", 0),
    City("Llanbradach", "United Kingdom", "Europe/London", 3746),
    City("Betws-y-Coed", "United Kingdom", "Europe/London", 1200),
    City("Pontlliw", "United Kingdom", "Europe/London", 1645),
    City("Herbrandston", "United Kingdom", "Europe/London", 0),
    City("Holywell", "United Kingdom", "Europe/London", 6969),
    City("Llangoed", "United Kingdom", "Europe/London", 849),
    City("Llangynog", "United Kingdom", "Europe/London", 0),
    City("Pont Rhyd-y-cyff", "United Kingdom", "Europe/London", 1505),
    City("Croeserw", "United Kingdom", "Europe/London", 1595),
    City("Carmarthen", "United Kingdom", "Europe/London", 15854),
    City("Four Crosses", "United Kingdom", "Europe/London", 1438),
    City("Coedpoeth", "United Kingdom", "Europe/London", 5723),
    City("Cwm", "United Kingdom", "Europe/London", 2739),
    City("Spittal", "United Kingdom", "Europe/London", 494),
    City("Rhosneigr", "United Kingdom", "Europe/London", 1008),
    City("Presteigne", "United Kingdom", "Europe/London", 2056),
    City("Prestatyn", "United Kingdom", "Europe/London", 18701),
    City("Borth", "United Kingdom", "Europe/London", 1269),
    City("Abergele", "United Kingdom", "Europe/London", 17769),
    City("Bedwas", "United Kingdom", "Europe/London", 8242),
    City("Blaenavon", "United Kingdom", "Europe/London", 5647),
    City("Briton Ferry", "United Kingdom", "Europe/London", 35179),
    City("Caldicot", "United Kingdom", "Europe/London", 11373),
    City("Gelligaer", "United Kingdom", "Europe/London", 17376),
    City("Gilfach Goch", "United Kingdom", "Europe/London", 2532),
    City("Knighton", "United Kingdom", "Europe/London", 3007),
    City("Lampeter", "United Kingdom", "Europe/London", 2970),
    City("Llanrhian", "United Kingdom", "Europe/London", 0),
    City("Marchwiel", "United Kingdom", "Europe/London", 1092),
    City("Rhondda", "United Kingdom", "Europe/London", 59450),
    City("Redwick", "United Kingdom", "Europe/London", 0),
    City("Nevern", "United Kingdom", "Europe/London", 0),
    City("Maesteg", "United Kingdom", "Europe/London", 21001),
    City("Llanrug", "United Kingdom", "Europe/London", 1916),
    City("Guilsfield", "United Kingdom", "Europe/London", 1220),
    City("Dyserth", "United Kingdom", "Europe/London", 2594),
    City("Llandovery", "United Kingdom", "Europe/London", 2065),
    City("Ynysybwl", "United Kingdom", "Europe/London", 3503),
    City("Llansadwrn", "United Kingdom", "Europe/London", 0),
    City("Llanfachraeth", "United Kingdom", "Europe/London", 0),
    City("Llanarth", "United Kingdom", "Europe/London", 0),
    City("Coity", "United Kingdom", "Europe/London", 41352),
    City("Bethesda", "United Kingdom", "Europe/London", 4735),
    City("Deeside", "United Kingdom", "Europe/London", 32000),
    City("Ystrad Mynach", "United Kingdom", "Europe/London", 0),
    City("Dale", "United Kingdom", "Europe/London", 0),
    City("Wenvoe", "United Kingdom", "Europe/London", 1155),
    City("Penygroes", "United Kingdom", "Europe/London", 1793),
    City("Maerdy", "United Kingdom", "Europe/London", 0),
    City("Llangathen", "United Kingdom", "Europe/London", 0),
    City("Llanbedr", "United Kingdom", "Europe/London", 385),
    City("Holt", "United Kingdom", "Europe/London", 0),
    City("Treorchy", "United Kingdom", "Europe/London", 8105),
    City("Rhoose", "United Kingdom", "Europe/London", 6160),
    City("Radyr", "United Kingdom", "Europe/London", 4710),
    City("Port Talbot", "United Kingdom", "Europe/London", 0),
    City("Penmaenmawr", "United Kingdom", "Europe/London", 2535),
    City("Pencader", "United Kingdom", "Europe/London", 1107),
    City("Moelfre", "United Kingdom", "Europe/London", 710),
    City("Llanwern", "United Kingdom", "Europe/London", 0),
    City("Penybont", "United Kingdom", "Europe/London", 0),
    City("Penarth", "United Kingdom", "Europe/London", 23437),
    City("Narberth", "United Kingdom", "Europe/London", 2265),
    City("Mostyn", "United Kingdom", "Europe/London", 1606),
    City("Llangwm", "United Kingdom", "Europe/London", 0),
    City("Llanfechain", "United Kingdom", "Europe/London", 0),
    City("Henllan", "United Kingdom", "Europe/London", 862),
    City("Six Bells", "United Kingdom", "Europe/London", 4797),
    City("Grovesend", "United Kingdom", "Europe/London", 1131),
    City("Llangybi", "United Kingdom", "Europe/London", 0),
    City("Ebbw Vale", "United Kingdom", "Europe/London", 33068),
    City("Betws", "United Kingdom", "Europe/London", 2253),
    City("Scleddau", "United Kingdom", "Europe/London", 0),
    City("Abercarn", "United Kingdom", "Europe/London", 10118),
    City("Abercanaid", "United Kingdom", "Europe/London", 5061),
    City("Langstone", "United Kingdom", "Europe/London", 0),
    City("Llanrhaeadr-ym-Mochnant", "United Kingdom", "Europe/London", 408),
    City("Tintern", "United Kingdom", "Europe/London", 750),
    City("Beddau", "United Kingdom", "Europe/London", 8134),
    City("Bargoed", "United Kingdom", "Europe/London", 13412),
    City("Maentwrog", "United Kingdom", "Europe/London", 0),
    City("Gorseinon", "United Kingdom", "Europe/London", 20581),
    City("Llanfyllin", "United Kingdom", "Europe/London", 1105),
    City("Llanidloes", "United Kingdom", "Europe/London", 2929),
    City("Llansantffraid Glan Conwy", "United Kingdom", "Europe/London", 1862),
    City("Llansteffan", "United Kingdom", "Europe/London", 424),
    City("Lledrod", "United Kingdom", "Europe/London", 0),
    City("Abertillery", "United Kingdom", "Europe/London", 10946),
    City("Barmouth", "United Kingdom", "Europe/London", 2315),
    City("Hawarden", "United Kingdom", "Europe/London", 25513),
    City("Llanfair Caereinion", "United Kingdom", "Europe/London", 1055),
    City("Llantwit Major", "United Kingdom", "Europe/London", 14384),
    City("Llysfaen", "United Kingdom", "Europe/London", 0),
    City("Mathry", "United Kingdom", "Europe/London", 0),
    City("Machen", "United Kingdom", "Europe/London", 2362),
    City("Llangollen", "United Kingdom", "Europe/London", 3466),
    City("Llandudno", "United Kingdom", "Europe/London", 15371),
    City("Llanddeusant", "United Kingdom", "Europe/London", 0),
    City("Llanboidy", "United Kingdom", "Europe/London", 0),
    City("Overton", "United Kingdom", "Europe/London", 965),
    City("Wrexham", "United Kingdom", "Europe/London", 65692),
    City("Y Felinheli", "United Kingdom", "Europe/London", 2284),
    City("Rogiet", "United Kingdom", "Europe/London", 1813),
    City("Clydach Vale", "United Kingdom", "Europe/London", 0),
    City("Llwynypia", "United Kingdom", "Europe/London", 2253),
    City("Nefyn", "United Kingdom", "Europe/London", 1373),
    City("Dolgellau", "United Kingdom", "Europe/London", 2688),
    City("Tregarth", "United Kingdom", "Europe/London", 1307),
    City("Beaumaris", "United Kingdom", "Europe/London", 1370),
    City("Milford Haven", "United Kingdom", "Europe/London", 13582),
    City("Mochdre", "United Kingdom", "Europe/London", 0),
    City("Newport", "United Kingdom", "Europe/London", 851),
    City("Seven Sisters", "United Kingdom", "Europe/London", 2123),
    City("Tonyrefail", "United Kingdom", "Europe/London", 9317),
    City("Treharris", "United Kingdom", "Europe/London", 12352),
    City("Pengam", "United Kingdom", "Europe/London", 0),
    City("Tredegar", "United Kingdom", "Europe/London", 14855),
    City("Price Town", "United Kingdom", "Europe/London", 2348),
    City("Aber", "United Kingdom", "Europe/London", 0),
    City("Bryneglwys", "United Kingdom", "Europe/London", 0),
    City("Cardigan", "United Kingdom", "Europe/London", 5301),
    City("Cowbridge", "United Kingdom", "Europe/London", 3804),
    City("Bangor", "United Kingdom", "Europe/London", 18322),
    City("Llangynog", "United Kingdom", "Europe/London", 0),
    City("Rhymney", "United Kingdom", "Europe/London", 8537),
    City("Rhosllannerchrugog", "United Kingdom", "Europe/London", 25362),
    City("Pontypool", "United Kingdom", "Europe/London", 35686),
    City("Morriston", "United Kingdom", "Europe/London", 0),
    City("Monmouth", "United Kingdom", "Europe/London", 10110),
    City("Mitchel Troy", "United Kingdom", "Europe/London", 0),
    City("Govilon", "United Kingdom", "Europe/London", 1447),
    City("Derwen", "United Kingdom", "Europe/London", 0),
    City("Chepstow", "United Kingdom", "Europe/London", 16169),
    City("Caernarfon", "United Kingdom", "Europe/London", 9730),
    City("Cefn Cribwr", "United Kingdom", "Europe/London", 1324),
    City("Merthyr Mawr", "United Kingdom", "Europe/London", 0),
    City("Deiniolen", "United Kingdom", "Europe/London", 1379),
    City("Rhyl", "United Kingdom", "Europe/London", 25874),
    City("Porthmadog", "United Kingdom", "Europe/London", 2981),
    City("Penally", "United Kingdom", "Europe/London", 848),
    City("Clydach", "United Kingdom", "Europe/London", 19307),
    City("Caerleon", "United Kingdom", "Europe/London", 8747),
    City("Llanharan", "United Kingdom", "Europe/London", 5755),
    City("Bow Street", "United Kingdom", "Europe/London", 1572),
    City("Burton", "United Kingdom", "Europe/London", 0),
    City("Llantwit Fardre", "United Kingdom", "Europe/London", 3992),
    City("Llandrindod Wells", "United Kingdom", "Europe/London", 5309),
    City("Llandrillo", "United Kingdom", "Europe/London", 0),
    City("Llanberis", "United Kingdom", "Europe/London", 1844),
    City("Corris", "United Kingdom", "Europe/London", 0),
    City("Cross Hands", "United Kingdom", "Europe/London", 4549),
    City("Deri", "United Kingdom", "Europe/London", 1006),
    City("Hay", "United Kingdom", "Europe/London", 0),
    City("Hirwaun", "United Kingdom", "Europe/London", 7247),
    City("Letterston", "United Kingdom", "Europe/London", 1245),
    City("Llangan", "United Kingdom", "Europe/London", 0),
    City("Llanllwchaiarn", "United Kingdom", "Europe/London", 0),
    City("Aberdare", "United Kingdom", "Europe/London", 31135),
    City("Newport", "United Kingdom", "Europe/London", 306844),
    City("Penllyn", "United Kingdom", "Europe/London", 0),
    City("Ponthir", "United Kingdom", "Europe/London", 0),
    City("Rhayader", "United Kingdom", "Europe/London", 1824),
    City("Ruabon", "United Kingdom", "Europe/London", 3091),
    City("Mold", "United Kingdom", "Europe/London", 10058),
    City("Tycroes", "United Kingdom", "Europe/London", 2156),
    City("New Quay", "United Kingdom", "Europe/London", 694),
    City("Pembroke", "United Kingdom", "Europe/London", 7552),
    City("Raglan", "United Kingdom", "Europe/London", 1183),
    City("Resolven", "United Kingdom", "Europe/London", 2068),
    City("Templeton", "United Kingdom", "Europe/London", 627),
    City("Whitford", "United Kingdom", "Europe/London", 0),
    City("Menai Bridge", "United Kingdom", "Europe/London", 4958),
    City("Pennard", "United Kingdom", "Europe/London", 0),
    City("New Tredegar", "United Kingdom", "Europe/London", 4208),
    City("Llangwm", "United Kingdom", "Europe/London", 0),
    City("Pwllheli", "United Kingdom", "Europe/London", 4076),
    City("Mochdre", "United Kingdom", "Europe/London", 0),
    City("Llanilar", "United Kingdom", "Europe/London", 1085),
    City("Leeswood", "United Kingdom", "Europe/London", 2282),
    City("Flint", "United Kingdom", "Europe/London", 26442),
    City("Ammanford", "United Kingdom", "Europe/London", 23709),
    City("Steynton", "United Kingdom", "Europe/London", 3000),
    City("Trefnant", "United Kingdom", "Europe/London", 993),
    City("Saint Clears", "United Kingdom", "Europe/London", 1605),
    City("Ruthin", "United Kingdom", "Europe/London", 5461),
    City("Pontarddulais", "United Kingdom", "Europe/London", 9073),
    City("Newbridge", "United Kingdom", "Europe/London", 6509),
    City("Llanvaches", "United Kingdom", "Europe/London", 0),
    City("Llandysul", "United Kingdom", "Europe/London", 1484),
    City("Llanfairpwllgwyngyll", "United Kingdom", "Europe/London", 3107),
    City("Porth", "United Kingdom", "Europe/London", 0),
    City("Pontyates", "United Kingdom", "Europe/London", 1449),
    City("Pembroke Dock", "United Kingdom", "Europe/London", 9753),
    City("Dyffryn Ardudwy", "United Kingdom", "Europe/London", 1654),
    City("New Inn", "United Kingdom", "Europe/London", 0),
    City("Abercynon", "United Kingdom", "Europe/London", 5983),
    City("Aberporth", "United Kingdom", "Europe/London", 1648),
    City("Aberystwyth", "United Kingdom", "Europe/London", 18749),
    City("Criccieth", "United Kingdom", "Europe/London", 1753),
    City("Haverfordwest", "United Kingdom", "Europe/London", 14596),
    City("Kidwelly", "United Kingdom", "Europe/London", 2782),
    City("Llanerchymedd", "United Kingdom", "Europe/London", 1133),
    City("Llanfair", "United Kingdom", "Europe/London", 0),
    City("Wiston", "United Kingdom", "Europe/London", 0),
    City("Newtown", "United Kingdom", "Europe/London", 11357),
    City("Pencoed", "United Kingdom", "Europe/London", 9166),
    City("Llantrisant", "United Kingdom", "Europe/London", 14422),
    City("Machynlleth", "United Kingdom", "Europe/London", 2235),
    City("Tenby", "United Kingdom", "Europe/London", 4696),
    City("Pentre", "United Kingdom", "Europe/London", 5424),
    City("Ambleston", "United Kingdom", "Europe/London", 0),
    City("Cardiff", "United Kingdom", "Europe/London", 447287),
    City("Dunvant", "United Kingdom", "Europe/London", 4383),
    City("Gilwern", "United Kingdom", "Europe/London", 2263),
    City("Magor", "United Kingdom", "Europe/London", 5941),
    City("Penrhyndeudraeth", "United Kingdom", "Europe/London", 1546),
    City("Rossett", "United Kingdom", "Europe/London", 2279),
    City("Trelech", "United Kingdom", "Europe/London", 0),
    City("Trawsfynydd", "United Kingdom", "Europe/London", 628),
    City("Usk", "United Kingdom", "Europe/London", 2834),
    City("Llansawel", "United Kingdom", "Europe/London", 0),
    City("Crumlin", "United Kingdom", "Europe/London", 5947),
    City("Llanfairfechan", "United Kingdom", "Europe/London", 3637),
    City("Llandybie", "United Kingdom", "Europe/London", 2813),
    City("Llanddowror", "United Kingdom", "Europe/London", 0),
    City("Kilgetty", "United Kingdom", "Europe/London", 1968),
    City("Cwmbran", "United Kingdom", "Europe/London", 48157),
    City("Cemaes Bay", "United Kingdom", "Europe/London", 1187),
    City("Castlemartin", "United Kingdom", "Europe/London", 0),
    City("Brynmawr", "United Kingdom", "Europe/London", 14924),
    City("Tonypandy", "United Kingdom", "Europe/London", 62545),
    City("Blaengwynfi", "United Kingdom", "Europe/London", 1362),
    City("Pontyclun", "United Kingdom", "Europe/London", 5794),
    City("Buckley", "United Kingdom", "Europe/London", 63576),
    City("Blaenau-Ffestiniog", "United Kingdom", "Europe/London", 4005),
    City("Harlech", "United Kingdom", "Europe/London", 1762),
    City("Bridgend", "United Kingdom", "Europe/London", 49597),
    City("Newcastle Emlyn", "United Kingdom", "Europe/London", 1883),
    City("Johnston", "United Kingdom", "Europe/London", 1941),
    City("Whitton", "United Kingdom", "Europe/London", 0),
    City("Valley", "United Kingdom", "Europe/London", 2361),
    City("Taibach", "United Kingdom", "Europe/London", 4582),
    City("Swansea", "United Kingdom", "Europe/London", 300352),
    City("Pontycymer", "United Kingdom", "Europe/London", 4288),
    City("Grosmont", "United Kingdom", "Europe/London", 0),
    City("Cwm", "United Kingdom", "Europe/London", 0),
    City("Brynamman", "United Kingdom", "Europe/London", 5693),
    City("Broughton", "United Kingdom", "Europe/London", 5974),
    City("Amlwch", "United Kingdom", "Europe/London", 3211),
    City("Merthyr Tydfil", "United Kingdom", "Europe/London", 43820),
    City("Glyncorrwg", "United Kingdom", "Europe/London", 1096),
    City("Llanddarog", "United Kingdom", "Europe/London", 0),
    City("Greenfield", "United Kingdom", "Europe/London", 2446),
    City("Southgate", "United Kingdom", "Europe/London", 2004),
    City("Goodwick", "United Kingdom", "Europe/London", 1720),
    City("Ferndale", "United Kingdom", "Europe/London", 7338),
    City("Cwmbach", "United Kingdom", "Europe/London", 4330),
    City("Bedlinog", "United Kingdom", "Europe/London", 1112),
    City("Gronant", "United Kingdom", "Europe/London", 1258),
    City("Blackwood", "United Kingdom", "Europe/London", 15476),
    City("Hook", "United Kingdom", "Europe/London", 838),
    City("Three Crosses", "United Kingdom", "Europe/London", 1583),
    City("Abergavenny", "United Kingdom", "Europe/London", 14651),
    City("Glandwr", "United Kingdom", "Europe/London", 1586),
    City("Bala", "United Kingdom", "Europe/London", 1974),
    City("Crynant", "United Kingdom", "Europe/London", 1602),
    City("Penyffordd", "United Kingdom", "Europe/London", 3554),
    City("Pontypridd", "United Kingdom", "Europe/London", 30420),
    City("Llangeler", "United Kingdom", "Europe/London", 3427),
    City("Hundleton", "United Kingdom", "Europe/London", 435),
    City("Abernant", "United Kingdom", "Europe/London", 0),
    City("Rhuddlan", "United Kingdom", "Europe/London", 3709),
    City("Queensferry", "United Kingdom", "Europe/London", 0),
    City("Llanrwst", "United Kingdom", "Europe/London", 3323),
    City("Llanelli", "United Kingdom", "Europe/London", 49591),
    City("Jeffreyston", "United Kingdom", "Europe/London", 0),
    City("Glanamman", "United Kingdom", "Europe/London", 4168),
    City("Nelson", "United Kingdom", "Europe/London", 12857),
    City("Pontyberem", "United Kingdom", "Europe/London", 1695),
    City("Fochriw", "United Kingdom", "Europe/London", 1250),
    City("Bodedern", "United Kingdom", "Europe/London", 1051),
    City("Aberfan", "United Kingdom", "Europe/London", 3547),
    City("Brecon", "United Kingdom", "Europe/London", 8250),
    City("Camrose", "United Kingdom", "Europe/London", 0),
    City("Abertridwr", "United Kingdom", "Europe/London", 6504),
    City("Llanharry", "United Kingdom", "Europe/London", 3035),
    City("Llangynidr", "United Kingdom", "Europe/London", 1036),
    City("Saundersfoot", "United Kingdom", "Europe/London", 3361),
    City("Talgarth", "United Kingdom", "Europe/London", 1268),
    City("Ogmore Vale", "United Kingdom", "Europe/London", 2436),
    City("Llanarth", "United Kingdom", "Europe/London", 503),
    City("Builth Wells", "United Kingdom", "Europe/London", 2829),
    City("Fishguard", "United Kingdom", "Europe/London", 3419),
    City("Bryn", "United Kingdom", "Europe/London", 923),
    City("Cwmtillery", "United Kingdom", "Europe/London", 4703),
    City("Tumble", "United Kingdom", "Europe/London", 4040),
    City("Crymych", "United Kingdom", "Europe/London", 704),
    City("Crofty", "United Kingdom", "Europe/London", 1012),
    City("Pen-clawdd", "United Kingdom", "Europe/London", 1935),
    City("Manorbier", "United Kingdom", "Europe/London", 0),
    City("Llanfynydd", "United Kingdom", "Europe/London", 0),
    City("Llandeilo", "United Kingdom", "Europe/London", 1795),
    City("Holyhead", "United Kingdom", "Europe/London", 11431),
    City("Cwmafan", "United Kingdom", "Europe/London", 5336),
    City("Mountain Ash", "United Kingdom", "Europe/London", 11230),
    City("Tregaron", "United Kingdom", "Europe/London", 1213),
    City("Ystradgynlais", "United Kingdom", "Europe/London", 0),
    City("Brynna", "United Kingdom", "Europe/London", 6686),
    City("Ystalyfera", "United Kingdom", "Europe/London", 10218),
    City("Blair", "United States", "America/Chicago", 1351),
    City("Lac du Flambeau", "United States", "America/Chicago", 1969),
    City("Ladysmith", "United States", "America/Chicago", 3188),
    City("Shorewood Hills", "United States", "America/Chicago", 2037),
    City("Union Grove", "United States", "America/Chicago", 4891),
    City("Watertown", "United States", "America/Chicago", 23819),
    City("Manitowoc", "United States", "America/Chicago", 33010),
    City("Little Chute", "United States", "America/Chicago", 11026),
    City("Lake Hallie", "United States", "America/Chicago", 6535),
    City("Whitefish Bay", "United States", "America/Chicago", 14110),
    City("King", "United States", "America/Chicago", 1750),
    City("Genoa City", "United States", "America/Chicago", 3029),
    City("Superior", "United States", "America/Chicago", 26579),
    City("Neillsville", "United States", "America/Chicago", 2409),
    City("Cuba City", "United States", "America/Chicago", 2055),
    City("Tichigan", "United States", "America/Chicago", 5133),
    City("Appleton", "United States", "America/Chicago", 74139),
    City("Augusta", "United States", "America/Chicago", 1532),
    City("Maple Bluff", "United States", "America/Chicago", 1340),
    City("Adams", "United States", "America/Chicago", 1893),
    City("Pardeeville", "United States", "America/Chicago", 2086),
    City("Okauchee Lake", "United States", "America/Chicago", 4422),
    City("Camp Lake", "United States", "America/Chicago", 3665),
    City("Cleveland", "United States", "America/Chicago", 1468),
    City("Dickeyville", "United States", "America/Chicago", 1039),
    City("Fall Creek", "United States", "America/Chicago", 1315),
    City("Hortonville", "United States", "America/Chicago", 2712),
    City("Howards Grove", "United States", "America/Chicago", 3271),
    City("Hustisford", "United States", "America/Chicago", 1100),
    City("Kewaunee", "United States", "America/Chicago", 2876),
    City("Markesan", "United States", "America/Chicago", 1417)
)